### ISSUE TITLE
Support for  lists of input files

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/data-manager-job-tester#1]
Some jobs can accept a variable number of inputs. e.g. in the python:
```
parser.add_argument('-f', '--fragments', nargs='+', required=True, help="Molfiles with fragments")
```
In the job YAML:
```
        properties:
          fragments:
            title: Fragment molecules
            multiple: true
            mime-types:
            - chemical/x-mdl-molfile
            type: file
```
In the test specification it seems these should be specified as:
```
    tests:
      simple-execution:
        inputs:
          fragments:
          - data/x0032_0A.mol
          - data/x0103_0A.mol
```
The tester does not support this:
```
$ jote
# Found 1 test
  ---
+ collection=fragmenstein job=frgmenstein-combine test=simple-execution
Traceback (most recent call last):
  File "/home/timbo/miniconda3/envs/im-jote/bin/jote", line 8, in <module>
    sys.exit(main())
  File "/home/timbo/miniconda3/envs/im-jote/lib/python3.10/site-packages/jote/jote.py", line 549, in main
    _test(args,
  File "/home/timbo/miniconda3/envs/im-jote/lib/python3.10/site-packages/jote/jote.py", line 308, in _test
    os.path.basename(job_definition.tests[job_test_name]
  File "/home/timbo/miniconda3/envs/im-jote/lib/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list

```

**Comment by alanbchristie** [comment]
OK - I’ll take a look shortly

**Comment by alanbchristie** [comment]
This is now supported in `0.1.15`
